[package]
name = "townscout_native"
version = "0.1.0"
edition = "2021"

[lib]
name = "t_hex"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22.0-beta.1", features = ["extension-module"] }
numpy = { version = "0.22.0-beta.1" }
rayon = "1.10.0"
